FROM rust:1-slim-bookworm AS builder
WORKDIR /src
COPY Cargo.toml Cargo.lock ./
COPY crates ./crates
RUN cargo build --release --bin ttyview

FROM scratch
COPY --from=builder /src/target/release/ttyview /ttyview
